//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TiendaColdlt.ObjetosNegocio
{
    using System;
    using System.Collections.Generic;
    
    public partial class Item
    {
        public int IdItem { get; set; }
        public int IdProducto { get; set; }
        public int IdFactura { get; set; }
        public int Cantidad { get; set; }
        public decimal ValorTotal { get; set; }
    
        public virtual Factura Factura { get; set; }
        public virtual Producto Producto { get; set; }
    }
}
